# Databricks notebook source
# MAGIC %sql
# MAGIC
# MAGIC CREATE CATALOG IF NOT EXISTS FMCG;
# MAGIC USE CATALOG FMCG;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE SCHEMA IF NOT EXISTS FMCG.gold;
# MAGIC CREATE SCHEMA IF NOT EXISTS FMCG.silver;
# MAGIC CREATE SCHEMA IF NOT EXISTS FMCG.bronze;

# COMMAND ----------

